version: '3.8'

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.8.1
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:adminpassword@db/airflow_db
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
  volumes:
    - ./dags:/opt/airflow/dags
    - ./data:/opt/airflow/data
  depends_on:
    - db

services:
  db:
    image: postgres:15
    container_name: cv_ranker_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: cv_ranker_db
      POSTGRES_MULTIPLE_DATABASES: cv_ranker_db,airflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  pgadmin:
    image: dpage/pgadmin4
    container_name: cv_ranker_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"

  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: cv_ranker_airflow_web
    restart: always
    depends_on:
      - db
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:adminpassword@db:5432/airflow_db
    logging:
      options:
        max-size: "10mb"
        max-file: "3"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./etl:/opt/airflow/etl
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db upgrade && airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: cv_ranker_airflow_scheduler
    restart: always
    depends_on:
      - db
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:adminpassword@db:5432/airflow_db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./etl:/opt/airflow/etl
    command: bash -c "airflow scheduler"

volumes:
  postgres_data: