x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:adminpassword@db:5432/airflow_db
    GCP_PROJECT_ID: ${GCP_PROJECT_ID}
    GEMINI_API_KEY: ${GEMINI_API_KEY}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./data:/opt/airflow/data
    - ./etl:/opt/airflow/etl
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./.env:/opt/airflow/.env
  depends_on:
    - db

services:
  db:
    image: postgres:15
    container_name: cv_ranker_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: cv_ranker_db
      POSTGRES_MULTIPLE_DATABASES: cv_ranker_db,airflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  pgadmin:
    image: dpage/pgadmin4
    container_name: cv_ranker_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"

  airflow-webserver:
    <<: *airflow-common
    container_name: cv_ranker_airflow_web
    restart: always
    depends_on:
      - db
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:adminpassword@db:5432/airflow_db
      - PYTHONPATH=/opt/airflow
      - AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT=google-cloud-platform://?extra__google_cloud_platform__project=${GCP_PROJECT_ID}&extra__google_cloud_platform__key_path=/opt/airflow/data/keys/gcp_key.json
    logging:
      options:
        max-size: "10mb"
        max-file: "3"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./etl:/opt/airflow/etl
      - ./.env:/opt/airflow/.env
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init && 
      airflow users create --username admin --firstname Gustavo --lastname Petrolini --role Admin --email admin@example.com --password ${AIRFLOW_PASSWORD} || true && 
      airflow webserver"

  airflow-scheduler:
    <<: *airflow-common
    container_name: cv_ranker_airflow_scheduler
    restart: always
    depends_on:
      - db
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:adminpassword@db:5432/airflow_db
      - PYTHONPATH=/opt/airflow
      - AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT=google-cloud-platform://?extra__google_cloud_platform__project=${GCP_PROJECT_ID}&extra__google_cloud_platform__key_path=/opt/airflow/data/keys/gcp_key.json
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./etl:/opt/airflow/etl
      - ./.env:/opt/airflow/.env
    command: bash -c "airflow scheduler"

volumes:
  postgres_data: