"""schema_db

Revision ID: a4c575362b1f
Revises: 
Create Date: 2026-05-15 11:26:56.795015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4c575362b1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('github_url', sa.Text(), nullable=True),
    sa.Column('vacancy_applied', sa.String(length=255), nullable=True),
    sa.Column('pdf_file_name', sa.String(length=255), nullable=True),
    sa.Column('pdf_storage_url', sa.Text(), nullable=True),
    sa.Column('pdf_pages', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('total_words', sa.Integer(), nullable=True),
    sa.Column('total_characters', sa.Integer(), nullable=True),
    sa.Column('must_have_score', sa.Integer(), nullable=True),
    sa.Column('nice_to_have_score', sa.Integer(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.Column('ranking_level', sa.String(length=50), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_strengths', sa.Text(), nullable=True),
    sa.Column('ai_weaknesses', sa.Text(), nullable=True),
    sa.Column('ai_seniority', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_table('vacancies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('seniority', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancies_id'), 'vacancies', ['id'], unique=False)
    op.create_table('candidate_keywords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=True),
    sa.Column('keyword_type', sa.String(length=50), nullable=True),
    sa.Column('keyword_weight', sa.Integer(), nullable=True),
    sa.Column('keyword_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_keywords_id'), 'candidate_keywords', ['id'], unique=False)
    op.create_table('vacancy_keywords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vacancy_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('keyword_type', sa.String(length=50), nullable=True),
    sa.Column('keyword_weight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancy_keywords_id'), 'vacancy_keywords', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_keywords_id'), table_name='vacancy_keywords')
    op.drop_table('vacancy_keywords')
    op.drop_index(op.f('ix_candidate_keywords_id'), table_name='candidate_keywords')
    op.drop_table('candidate_keywords')
    op.drop_index(op.f('ix_vacancies_id'), table_name='vacancies')
    op.drop_table('vacancies')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
